routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [
    'uses' => 'BlogController@landingPage',
    'as'   => 'landing-page'
]);
Route::get('/services', [
    'uses' => 'BlogController@services',
    'as'   => 'services'
]);
Route::get('/about', [
    'uses' => 'BlogController@about',
    'as'   => 'about'
]);
Route::get('/contact-us', [
    'uses' => 'BlogController@contactUs',
    'as'   => 'contact-us'
]);
Route::get('/create-value', [
    'uses' => 'BlogController@createValue',
    'as'   => 'create-value'
]);
Route::get('/how-we-work', [
    'uses' => 'BlogController@howWeWork',
    'as'   => 'how-we-work'
]);
Route::get('/blog', [
    'uses' => 'BlogController@index',
    'as'   => 'blog'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as'   => 'blog.show'
]);

Route::post('/blog/{post}/comments', [
    'uses' => 'CommentsController@store',
    'as'   => 'blog.comments'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as'   => 'category'
]);

Route::get('/author/{author}', [
    'uses' => 'BlogController@author',
    'as'   => 'author'
]);

Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as'   => 'tag'
]);

Route::post('/blog/{post}/comments', [
    'uses' => 'CommentsController@store',
    'as' => 'blog.comments'
]);

Route::auth();

Route::get('/home', 'Backend\HomeController@index');
Route::get('/edit-account', 'Backend\HomeController@edit');
Route::put('/edit-account', 'Backend\HomeController@update');

Route::put('/backend/blog/restore/{blog}', [
    'uses' => 'Backend\BlogController@restore',
    'as'   => 'backend.blog.restore'
]);
Route::delete('/backend/blog/force-destroy/{blog}', [
    'uses' => 'Backend\BlogController@forceDestroy',
    'as'   => 'backend.blog.force-destroy'
]);
Route::resource('/backend/blog', 'Backend\BlogController',['as' =>'backend']);

Route::resource('/backend/categories', 'Backend\CategoriesController',['as' =>'backend']);

Route::get('/backend/users/confirm/{users}', [
    'uses' => 'Backend\UsersController@confirm',
    'as' => 'backend.users.confirm'
]);
Route::resource('/backend/users', 'Backend\UsersController',['as' =>'backend']);
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;

class Post extends Model
{
    use SoftDeletes;

    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at', 'category_id', 'image'];
    protected $dates    = ['published_at'];

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function createComment(array $data)
    {
        $this->comments()->create($data);
    }

    public function createTags($str)
    {
        $tags = explode(",", $str);
        $tagIds = [];

        foreach ($tags as $tag)
        {
            $newTag = Tag::firstOrCreate([
                'slug' => str_slug($tag),
                'name' => ucwords(trim($tag))
            ]);

            $tagIds[] = $newTag->id;
        }

        $this->tags()->sync($tagIds);
    }

    public function setPublishedAtAttribute($value)
    {
        $this->attributes['published_at'] = $value ?: NULL;
    }

    public function getTagsListAttribute()
    {
        return $this->tags->pluck('name');
    }

    public function getImageUrlAttribute($value)
    {
        $imageUrl = "";

        if ( ! is_null($this->image))
        {
            $directory = config('cms.image.directory');
            $imagePath = public_path() . "/{$directory}/" . $this->image;
            if (file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $this->image);
        }

        return $imageUrl;
    }

    public function getImageThumbUrlAttribute($value)
    {
        $imageUrl = "";

        if ( ! is_null($this->image))
        {
            $directory = config('cms.image.directory');
            $ext       = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $this->image);
            $imagePath = public_path() . "/{$directory}/" . $thumbnail;
            if (file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $thumbnail);
        }

        return $imageUrl;
    }

    public function getDateAttribute($value)
    {
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getBodyHtmlAttribute($value)
    {
        return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
    }

    public function getExcerptHtmlAttribute($value)
    {
        return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : NULL;
    }

    public function getTagsHtmlAttribute()
    {
        $anchors = [];
        foreach($this->tags as $tag) {
            $anchors[] = '<a href="' . route('tag', $tag->slug) . '">' . $tag->name . '</a>';
        }
        return implode(", ", $anchors);
    }

    public function dateFormatted($showTimes = false)
    {
        $format = "d/m/Y";
        if ($showTimes) $format = $format . " H:i:s";
        return $this->created_at->format($format);
    }

    public function commentsNumber($label = 'Comment')
    {
        $commentsNumber = $this->comments->count();
        return $commentsNumber . " " . str_plural($label, $commentsNumber);
    }

    public function publicationLabel()
    {
        if ( ! $this->published_at) {
            return '<span class="label label-warning">Draft</span>';
        }
        elseif ($this->published_at && $this->published_at->isFuture()) {
            return '<span class="label label-info">Schedule</span>';
        }
        else {
            return '<span class="label label-success">Published</span>';
        }
    }


    public function scopeLatestFirst($query)
    {
        return $query->orderBy('published_at', 'desc');
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where("published_at", "<=", Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where("published_at", ">", Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull("published_at");
    }

    public static function archives()
    {
        if (env("DB_CONNECTION") === 'pgsql') {
            return static::selectRaw('count(id) as post_count, extract(year from published_at) as year, extract(month from published_at) as month')
                            ->published()
                            ->groupBy('year', 'month')
                            ->orderByRaw('min(published_at) desc')
                            ->get();
        }
        else {
            return static::selectRaw('count(id) as post_count, year(published_at) year, month(published_at) month')
                            ->published()
                            ->groupBy('year', 'month')
                            ->orderByRaw('min(published_at) desc')
                            ->get();

        }
    }

    public function scopeFilter($query, $filter)
    {
        if (isset($filter['month']) && $month = $filter['month']) {
            if (env('DB_CONNECTION') === 'pgsql') {
                $query->whereRaw('extract(month from published_at) = ?', [$month]);
            }
            else {
                $query->whereRaw('month(published_at) = ?', [$month]);
            }
        }

        if (isset($filter['year']) && $year = $filter['year']) {
            if (env('DB_CONNECTION') === 'pgsql') {
                $query->whereRaw('extract(year from published_at) = ?', [$year]);
            }
            else {
                $query->whereRaw('year(published_at) = ?', [$year]);
            }
        }

        // check if any term entered
        if (isset($filter['term']) && $term = strtolower($filter['term']))
        {
            $query->where(function($q) use ($term) {
                // $q->whereHas('author', function($qr) use ($term) {
                //     $qr->where('name', 'LIKE', "%{$term}%");
                // });
                // $q->orWhereHas('category', function($qr) use ($term) {
                //     $qr->where('title', 'LIKE', "%{$term}%");
                // });
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
            });
        }
    }
}

resources/views/layouts/inc/blogs.blade.php
<div class="col-lg-8 col-md-12">
    @if (! $posts->count())
        <div class="alert alert-warning">
            <p>Nothing Found</p>
        </div>
    @else
        @include('blog.alert')

        @foreach($posts as $post)

            <article class="post-item">
                @if ($post->image_url)
                    <div class="post-item-image">
                        <a href="{{ route('blog.show', $post->slug) }}">
                            <img src="{{ $post->image_url }}" alt="" >
                        </a>
                    </div>
                @endif

                <div class="post-item-body">
                    <div class="padding-10">
                        <h2><a href="{{ route('blog.show', $post->slug) }}">{{ $post->title }}</a></h2>
                        {!! $post->excerpt_html !!}
                    </div>

                    <div class="post-meta padding-10 clearfix">
                        <div class="pull-left">
                            <ul class="post-meta-group">
                                <li><i class="fa fa-user"></i><a href="{{ route('author', $post->author->slug) }}"> {{ $post->author->name }}</a></li>
                                <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                                <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}"> {{ $post->category->title }}</a></li>
                                <li><i class="fa fa-tag"></i>{!! $post->tags_html !!}</li>
                                <li><i class="fa fa-comments"></i><a href="{{ route('blog.show', $post->slug) }}#post-comments">{{ $post->commentsNumber() }}</a></li>
                            </ul>
                        </div>
                        <div class="pull-right">
                            <a href="{{ route('blog.show', $post->slug) }}">Continue Reading &raquo;</a>
                        </div>
                    </div>
                </div>
            </article>

        @endforeach

    @endif

    <nav>
      {{ $posts->appends(request()->only(['term', 'month', 'year']))->links() }}
    </nav>
</div>

resources/views/layouts/inc/header-section.blade.php
<header  style="height:200px;" class="mb-4">

        <div class="overlay"></div>
        
        <div class="container h-100">
            <div class="d-flex text-center h-100">
            <div class="my-auto w-100 text-white">
    
          
                {!!$title=''!!}                        
                
                
            </div>
            </div>
        </div>
    
        </div>
    
    </header>

resources/views/layouts/inc/landingblogs.blade.php
<div class="col-md-8">
    @if (! $posts->count())
        <div class="alert alert-warning">
           
        </div>
    @else
        @include('blog.alert')

        @foreach($posts as $post)

            <article class="post-item">
                @if ($post->image_url)
                    <div class="post-item-image">
                        <a href="{{ route('blog.show', $post->slug) }}">
                            <img src="{{ $post->image_url }}" alt="" >
                        </a>
                    </div>
                @endif

                <div class="post-item-body">
                    <div class="padding-10">
                        <h2><a href="{{ route('blog.show', $post->slug) }}">{{ $post->title }}</a></h2>
                        {!! $post->excerpt_html !!}
                    </div>

                    <div class="post-meta padding-10 clearfix">
                        <div class="pull-left">
                            <ul class="post-meta-group">
                                <li><i class="fa fa-user"></i><a href="{{ route('author', $post->author->slug) }}"> {{ $post->author->name }}</a></li>
                                <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                                <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}"> {{ $post->category->title }}</a></li>
                                <li><i class="fa fa-tag"></i>{!! $post->tags_html !!}</li>
                                <li><i class="fa fa-comments"></i><a href="{{ route('blog.show', $post->slug) }}#post-comments">{{ $post->commentsNumber() }}</a></li>
                            </ul>
                        </div>
                        <div class="pull-right">
                            <a href="{{ route('blog.show', $post->slug) }}">Continue Reading &raquo;</a>
                        </div>
                    </div>
                </div>
            </article>

        @endforeach

    @endif

    <nav>
      {{ $posts->appends(request()->only(['term', 'month', 'year']))->links() }}
    </nav>
</div>

resources/views/layouts/inc/navbar.blade.php
<div class="container-fluid main-menubar">

        <nav class="navbar container-fluid navbar-expand-lg navbar-dark bg-transparent">
            <a class="logo mr-2 ml-2" href="/">
              <img width="150px" height="50px" src="/img/Ndebi Tech Logo.png" alt="logo"/>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> <i class="fa fa-bars" aria-hidden="true"></i> </span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="blog">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-none" href="/services">Services</a>
                  </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Services
                  </a>
                  <div class="dropdown-menu row" aria-labelledby="navbarDropdown">
                      <h5 class="text-center">All Services</h5>
                    <div class="row">
                      <div class="col m-2 w-100">
                          <h5 class="text-center">Section One</h5>
                        <ul class="navbar-nav mr-auto">
                            <li  class="nav-item">
                                <a class="dropdown-item" href="/services">Something else here</a>
                            </li>
                            <li  class="nav-item">
                                <a class="dropdown-item" href="#">Something else here</a>
                            </li>
                            <li  class="nav-item">
                                <a class="dropdown-item" href="#">Something else here</a>
                            </li>
                        </ul>
                      </div>
                      <div class="col m-2 w-100">
                        <h5 class="text-center">Section Two</h5>
                          <ul class="navbar-nav mr-auto">
                              <li  class="nav-item">
                                  <a class="dropdown-item" href="#">Something else here</a>
                              </li>
                              <li  class="nav-item">
                                  <a class="dropdown-item" href="#">Something else here</a>
                              </li>
                              <li  class="nav-item">
                                  <a class="dropdown-item" href="#">Something else here</a>
                              </li>
                          </ul>
                      </div>
                    </div>
                  </div>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="/create-value" tabindex="-1" aria-disabled="true">How create Value</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="/how-we-work" tabindex="-1" aria-disabled="true">How we Work</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/about" tabindex="-1" aria-disabled="true">About</a>
                      </li>

                <li class="nav-item">
                    <a class="nav-link" href="/contact-us" tabindex="-1" aria-disabled="true">Contact Us</a>
                  </li>
              </ul>
              <form class="form-inline my-1 my-lg-0"  action="{{ route('blog') }}">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="{{ request('term') }}" name="term">
                <button class="btn btn-outline-info my-1 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>

        </div>

      {{-- navigation bar --}}
        

resources/views/layouts/inc/navbar2.blade.php
<div class="swipe-menu default-theme">
    <div class="logo">
        <a href="/"><img width="175px" height="75px" src="/img/Ndebi Tech Logo.png" alt="logo"/></a>
    </div>
    <div class="codehim-search-trigger"></div>
    <div class="codehim-search">
       <form  class="form-inline my-2 my-lg-0"  action="{{ route('blog') }}">
          <input class="search-text form-control mr-sm-2" placeholder="Type to search..." autocomplete="on" value="{{ request('term') }}" name="term" type="text" />
          <button class="search-now btn btn-success" name="submit" type="submit" disabled="true"> Search </button>
       </form>
       <div class="back-arrow"></div>
    </div>
    <!--//codehim-search-->
    <!--Navigation Icon-->
    <div class="nav-icon">
       <span></span>
       <span></span>
       <span></span>
    </div>
    <nav class="codehim-nav">
       <div class="tab-container">
          <span class="tab-name tab-name1-active"> My Projects</span>
          <span class="tab-name"> Tutorials  </span>
       </div>
       <!--//Tab Container-->
       <div class="tab tab-active">
          <ul class="menu-item">
             <li> <a href="#1"> Website Templates </a> </li>
             <li class="has-sub">
                <span class="dropdown-heading"> Jquery Projects</span> <!--Do not add any link in li that has sub items // Use span for dropdown heading-->
                <ul>
                   <li><a href="#2"> Sub Item 1</a> </li>
                   <li> <a href="#2"> Sub Item 2 </a> </li>
                   <li> <a href="#2"> Sub Item 3 </a> </li>
                   <li> <a href="#2"> Sub Item 4 </a> </li>
                </ul>
             </li>
             <li> <a href="#1"> Recommended </a> </li>
             <li> <a href="#1"> Top Ten</a> </li>
          </ul>
          <ul class="my-codehim">
             <li> <a class="help" href="#1"> Help & Feedback </a> </li>
             <li> <a class="updates" href="#1"> Subscribe Me</a> </li>
             <li> <a class="request" href="#1"> Request for Code</a></li>
          </ul>
          <div class="social">
            
             <div class="facebook"></div>
             <div class="twitter"></div>
             <div class="gplus"> </div>
          </div>
          <!--//social-->
       </div>
       <!--//Tab-->
       <div class="tab">
          <ul class="menu-item">
             <li> <a href="#1"> Latest Updates </a> </li>
             <li> <a href="#1"> How to Coding </a> </li>
             <li class="has-sub">
                <span class="dropdown-heading"> Designing Tutorials</span>
                <ul>
                   <li><a href="#2"> Sub Item 1</a> </li>
                   <li> <a href="#2"> Sub Item 2 </a> </li>
                   <li> <a href="#2"> Sub Item 3 </a> </li>
                   <li> <a href="#2"> Sub Item 4 </a> </li>
                   <li> <a href="#2"> Sub Item 5 </a> </li>
                </ul>
             </li>
             <li class="has-sub">
                <span class="dropdown-heading"> Development Tutorials</span>
                <ul>
                   <li><a href="#2"> Sub Item 1</a> </li>
                   <li> <a href="#2"> Sub Item 2 </a> </li>
                   <li> <a href="#2"> Sub Item 3 </a> </li>
                </ul>
             </li>
             <li> <a href="#1"> Most Recently</a> </li>
          </ul>
       </div>
       <!--//Tab-->
    </nav>
 </div>
 {{-- <div class="dim-overlay"> </div> --}}